# Generated by Django 2.0.5 on 2018-05-22 16:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('codigo_documento', models.CharField(max_length=50)),
                ('fecha_emision', models.DateField()),
                ('ruta_pdf', models.FilePathField()),
                ('estado', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('FACTURA_BOLETA', 'FACTURA_BOLETA'), ('GUIA DE REMISION', 'GUIA DE REMISION'), ('ORDEN DE COMPRA', 'ORDEN DE COMPRA'), ('ACTA DE CONFORMIDAD', 'ACTA DE CONFORMIDAD'), ('COMPROBANTE DE SALIDA', 'COMPROBANTE DE SALIDA'), ('GARANTIAS', 'GARANTIAS'), ('TRASLADOS', 'TRASLADOS'), ('OTROS', 'OTROS')], default='FACTURA_BOLETA', max_length=50)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('razon_social', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=60)),
                ('representante_legal', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='EstadoProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='EstadoRecurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Historial_Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('fecha_historial', models.DateField()),
                ('observaciones', models.TextField()),
                ('idEstadoProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.EstadoProyecto')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Historial_Recursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('fecha_historial', models.DateField()),
                ('observaciones', models.TextField()),
                ('idEstadoRecurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.EstadoRecurso')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Miembro_Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField()),
                ('fecha_miembro_proyecto', models.DateField()),
                ('estado_miembro_proyecto', models.CharField(max_length=30)),
                ('idCargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Cargos')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='MiembroProyecto_RecursoProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('observacion', models.TextField()),
                ('estado', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField()),
                ('idMiembro_Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Miembro_Proyecto')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Miembros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('dni', models.CharField(max_length=30)),
                ('fecha_ingreso', models.DateField(default=datetime.date.today)),
                ('foto', models.ImageField(default='images/miembros/None/no-img.jpg', upload_to='images/miembros/')),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=60)),
                ('fecha_nacimiento', models.DateField(default=datetime.date.today)),
                ('aleatorio', models.CharField(default='QAWSEDRFTYUHI', max_length=25)),
                ('grado_academico', models.CharField(choices=[('Estudiante de Pregrado', 'Estudiante de Pregrado'), ('Estudiante de Pregrado', 'Estudiante de Postgrado')], default='Estudiante de Pregrado', max_length=50)),
                ('estado_miembro', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO'), ('PENDIENTE', 'PENDIENTE')], default='PENDIENTE', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Miembros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=500)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField(max_length=100)),
                ('foto', models.ImageField(default='images/proyectos/None/no-img.jpg', upload_to='images/proyectos/')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Recurso_Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('idDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Documento')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Recurso_Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=30)),
                ('fecha_recurso_proyecto', models.DateField()),
                ('idProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Proyectos')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='recursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('cod_patrimonio', models.CharField(max_length=50)),
                ('nro_producto', models.CharField(max_length=50)),
                ('nro_serie', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(default='images/recursos/None/no-img.jpg', upload_to='images/recursos/')),
                ('fecha_ingreso', models.DateField(max_length=100)),
                ('caracteristicas', models.TextField(max_length=100)),
                ('tipo', models.CharField(choices=[('Tangibles', 'Tangibles'), ('Intangibles', 'Intangibles')], default='Tangibles', max_length=50)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ResultadoProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField()),
                ('fecha_resultado', models.DateField()),
                ('idProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Proyectos')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='recurso_proyecto',
            name='idRecurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.recursos'),
        ),
        migrations.AddField(
            model_name='recurso_documento',
            name='idRecurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.recursos'),
        ),
        migrations.AddField(
            model_name='miembroproyecto_recursoproyecto',
            name='idRecurso_Proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Recurso_Proyecto'),
        ),
        migrations.AddField(
            model_name='miembro_proyecto',
            name='idMiembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Miembros'),
        ),
        migrations.AddField(
            model_name='miembro_proyecto',
            name='idProyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Proyectos'),
        ),
        migrations.AddField(
            model_name='historial_recursos',
            name='idRecurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.recursos'),
        ),
        migrations.AddField(
            model_name='historial_proyecto',
            name='idProyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Proyectos'),
        ),
        migrations.AddField(
            model_name='documento',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Entidad'),
        ),
    ]
