# Generated by Django 2.0.5 on 2018-06-08 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='ruta_pdf',
            field=models.FileField(default='docs/documentos/None/no-img.jpg', upload_to='docs/documentos/'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('FACTURA_BOLETA', 'FACTURA BOLETA'), ('GUIA DE REMISION', 'GUIA DE REMISION'), ('ORDEN DE COMPRA', 'ORDEN DE COMPRA'), ('ACTA DE CONFORMIDAD', 'ACTA DE CONFORMIDAD'), ('COMPROBANTE DE SALIDA', 'COMPROBANTE DE SALIDA'), ('GARANTIAS', 'GARANTIAS'), ('TRASLADOS', 'TRASLADOS'), ('OTROS', 'OTROS')], default='FACTURA_BOLETA', max_length=50),
        ),
        migrations.AlterField(
            model_name='recurso_proyecto',
            name='idRecurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_recurso', to='Inventario.recursos'),
        ),
    ]
