# Generated by Django 2.0.5 on 2018-07-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_auto_20180608_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso_proyecto',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=50),
        ),
    ]
