# Generated by Django 2.0 on 2018-07-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_auto_20180724_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='codigo_documento',
            field=models.CharField(max_length=300),
        ),
    ]
