# Generated by Django 2.0 on 2018-08-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0005_auto_20180731_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargos',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='miembro_proyecto',
            options={'ordering': ('-idProyecto',)},
        ),
        migrations.AlterModelOptions(
            name='recurso_proyecto',
            options={'ordering': ('-idProyecto',)},
        ),
        migrations.AlterField(
            model_name='miembroproyecto_recursoproyecto',
            name='fecha',
            field=models.DateField(),
        ),
    ]
