# Generated by Django 2.0 on 2018-08-02 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0006_auto_20180802_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembroproyecto_recursoproyecto',
            name='fecha',
            field=models.DateField(default=datetime.date(2018, 8, 2)),
        ),
    ]
