# Generated by Django 2.0 on 2018-08-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0010_recursos_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='estado',
            field=models.CharField(default='ACTIVO', max_length=50),
        ),
        migrations.AlterField(
            model_name='miembros',
            name='grado_academico',
            field=models.CharField(choices=[('Estudiante de Pregrado', 'Estudiante de Pregrado'), ('Estudiante de Postgrado', 'Estudiante de Postgrado')], default='Estudiante de Pregrado', max_length=50),
        ),
    ]
