# Generated by Django 2.0.2 on 2019-01-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0011_auto_20180807_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembros',
            name='grado_academico',
            field=models.CharField(choices=[('Estudiante de Pregrado', 'Estudiante de Pregrado'), ('Estudiante de Postgrado', 'Estudiante de Postgrado'), ('Magister', 'Magister')], default='Estudiante de Pregrado', max_length=50),
        ),
    ]
