# Generated by Django 2.0.2 on 2019-01-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0013_auto_20190106_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembroproyecto_recursoproyecto',
            name='estado',
            field=models.CharField(choices=[('SOLICITADO', 'SOLICITADO'), ('DENEGADO', 'DENEGADO'), ('PRESTADO', 'PRESTADO'), ('DEVUELTO', 'DEVUELTO'), ('OBSERVADO', 'OBSERVADO')], default='SOLICITADO', max_length=50),
        ),
    ]
